openapi: 3.0.0
info:
  version: 2018-11-14
  x-release: v4
  title: Managed Streaming for Kafka Clusters Configurations API
  description: "\n               <p>The operations for managing an Amazon MSK cluster.</p>"
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: kafka
  x-aws-signingName: kafka
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/kafka-2018-11-14.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://kafka.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Kafka multi-region endpoint
- url: https://kafka.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Kafka multi-region endpoint
- url: http://kafka.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Kafka endpoint for China (Beijing) and China (Ningxia)
- url: https://kafka.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Kafka endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Configurations
paths:
  /v1/configurations:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateConfiguration
      description: "\n            <p>Creates a new MSK configuration.</p>"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateConfigurationResponse'
              examples:
                CreateConfiguration200Example:
                  summary: Default CreateConfiguration 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    CreationTime: example-value
                    LatestRevision: example-value
                    Name: example-resource
                    State: example-value
        '480':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                CreateConfiguration480Example:
                  summary: Default CreateConfiguration 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                CreateConfiguration481Example:
                  summary: Default CreateConfiguration 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: UnauthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedException'
              examples:
                CreateConfiguration482Example:
                  summary: Default CreateConfiguration 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                CreateConfiguration483Example:
                  summary: Default CreateConfiguration 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                CreateConfiguration484Example:
                  summary: Default CreateConfiguration 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                CreateConfiguration485Example:
                  summary: Default CreateConfiguration 485 response
                  x-microcks-default: true
                  value: {}
        '486':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                CreateConfiguration486Example:
                  summary: Default CreateConfiguration 486 response
                  x-microcks-default: true
                  value: {}
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - name
              - serverProperties
              properties:
                description:
                  description: "\n            <p>The description of the configuration.</p>"
                  type: string
                kafkaVersions:
                  description: "\n            <p>The versions of Apache Kafka with which you can use this MSK configuration.</p>"
                  type: array
                  items:
                    $ref: '#/components/schemas/__string'
                name:
                  description: "\n            <p>The name of the configuration.</p>"
                  type: string
                serverProperties:
                  description: "\n            <p>Contents of the <filename>server.properties</filename> file. When using the API, you must ensure that the contents of the file are base64 encoded. \n               When using the AWS Management Console, the SDK, or the AWS CLI, the contents of <filename>server.properties</filename> can be in plaintext.</p>"
                  type: string
      summary: Amazon MSK Create Configuration
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Configurations
    get:
      operationId: ListConfigurations
      description: "\n            <p>Returns a list of all the MSK configurations in this Region.</p>"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListConfigurationsResponse'
              examples:
                ListConfigurations200Example:
                  summary: Default ListConfigurations 200 response
                  x-microcks-default: true
                  value:
                    Configurations: example-value
                    NextToken: example-value
        '480':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                ListConfigurations480Example:
                  summary: Default ListConfigurations 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                ListConfigurations481Example:
                  summary: Default ListConfigurations 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: UnauthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedException'
              examples:
                ListConfigurations482Example:
                  summary: Default ListConfigurations 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                ListConfigurations483Example:
                  summary: Default ListConfigurations 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                ListConfigurations484Example:
                  summary: Default ListConfigurations 484 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: maxResults
        in: query
        required: false
        description: "\n            <p>The maximum number of results to return in the response. If there are more results, the response includes a NextToken parameter.</p>"
        schema:
          type: integer
          minimum: 1
          maximum: 100
      - name: nextToken
        in: query
        required: false
        description: "\n            <p>The paginated results marker. When the result of the operation is truncated, the call returns NextToken in the response. \n            To get the next batch, provide this token in your next request.</p>"
        schema:
          type: string
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      summary: Amazon MSK List Configurations
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Configurations
  /v1/configurations/{arn}:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    delete:
      operationId: DeleteConfiguration
      description: "\n            <p>Deletes an MSK Configuration.</p>"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteConfigurationResponse'
              examples:
                DeleteConfiguration200Example:
                  summary: Default DeleteConfiguration 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    State: example-value
        '480':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                DeleteConfiguration480Example:
                  summary: Default DeleteConfiguration 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                DeleteConfiguration481Example:
                  summary: Default DeleteConfiguration 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                DeleteConfiguration482Example:
                  summary: Default DeleteConfiguration 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                DeleteConfiguration483Example:
                  summary: Default DeleteConfiguration 483 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: arn
        in: path
        required: true
        description: "\n            <p>The Amazon Resource Name (ARN) that uniquely identifies an MSK configuration.</p>"
        schema:
          type: string
      summary: Amazon MSK Delete Configuration
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Configurations
    get:
      operationId: DescribeConfiguration
      description: "\n            <p>Returns a description of this MSK configuration.</p>"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeConfigurationResponse'
              examples:
                DescribeConfiguration200Example:
                  summary: Default DescribeConfiguration 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    CreationTime: example-value
                    Description: Example description
                    KafkaVersions: example-value
                    LatestRevision: example-value
        '480':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                DescribeConfiguration480Example:
                  summary: Default DescribeConfiguration 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: UnauthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedException'
              examples:
                DescribeConfiguration481Example:
                  summary: Default DescribeConfiguration 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                DescribeConfiguration482Example:
                  summary: Default DescribeConfiguration 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                DescribeConfiguration483Example:
                  summary: Default DescribeConfiguration 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                DescribeConfiguration484Example:
                  summary: Default DescribeConfiguration 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                DescribeConfiguration485Example:
                  summary: Default DescribeConfiguration 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: arn
        in: path
        required: true
        description: "\n            <p>The Amazon Resource Name (ARN) that uniquely identifies an MSK configuration and all of its revisions.</p>"
        schema:
          type: string
      summary: Amazon MSK Describe Configuration
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Configurations
    put:
      operationId: UpdateConfiguration
      description: "\n            <p>Updates an MSK configuration.</p>"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateConfigurationResponse'
              examples:
                UpdateConfiguration200Example:
                  summary: Default UpdateConfiguration 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    LatestRevision: example-value
        '480':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                UpdateConfiguration480Example:
                  summary: Default UpdateConfiguration 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: UnauthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedException'
              examples:
                UpdateConfiguration481Example:
                  summary: Default UpdateConfiguration 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                UpdateConfiguration482Example:
                  summary: Default UpdateConfiguration 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                UpdateConfiguration483Example:
                  summary: Default UpdateConfiguration 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                UpdateConfiguration484Example:
                  summary: Default UpdateConfiguration 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                UpdateConfiguration485Example:
                  summary: Default UpdateConfiguration 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: arn
        in: path
        required: true
        description: "\n            <p>The Amazon Resource Name (ARN) of the configuration.</p>"
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - serverProperties
              properties:
                description:
                  description: "\n            <p>The description of the configuration revision.</p>"
                  type: string
                serverProperties:
                  description: "\n            <p>Contents of the <filename>server.properties</filename> file. When using the API, you must ensure that the contents of the file are base64 encoded. \n               When using the AWS Management Console, the SDK, or the AWS CLI, the contents of <filename>server.properties</filename> can be in plaintext.</p>"
                  type: string
      summary: Amazon MSK Update Configuration
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Configurations
  /v1/configurations/{arn}/revisions/{revision}:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: DescribeConfigurationRevision
      description: "\n            <p>Returns a description of this revision of the configuration.</p>"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeConfigurationRevisionResponse'
              examples:
                DescribeConfigurationRevision200Example:
                  summary: Default DescribeConfigurationRevision 200 response
                  x-microcks-default: true
                  value:
                    Arn: arn:aws:service:us-east-1:123456789012:resource/example
                    CreationTime: example-value
                    Description: Example description
                    Revision: example-value
                    ServerProperties: example-value
        '480':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                DescribeConfigurationRevision480Example:
                  summary: Default DescribeConfigurationRevision 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: UnauthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedException'
              examples:
                DescribeConfigurationRevision481Example:
                  summary: Default DescribeConfigurationRevision 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                DescribeConfigurationRevision482Example:
                  summary: Default DescribeConfigurationRevision 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                DescribeConfigurationRevision483Example:
                  summary: Default DescribeConfigurationRevision 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                DescribeConfigurationRevision484Example:
                  summary: Default DescribeConfigurationRevision 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                DescribeConfigurationRevision485Example:
                  summary: Default DescribeConfigurationRevision 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: arn
        in: path
        required: true
        description: "\n            <p>The Amazon Resource Name (ARN) that uniquely identifies an MSK configuration and all of its revisions.</p>"
        schema:
          type: string
      - name: revision
        in: path
        required: true
        description: "\n            <p>A string that uniquely identifies a revision of an MSK configuration.</p>"
        schema:
          type: integer
      summary: Amazon MSK Describe Configuration Revision
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Configurations
  /v1/configurations/{arn}/revisions:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListConfigurationRevisions
      description: "\n            <p>Returns a list of all the MSK configurations in this Region.</p>"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListConfigurationRevisionsResponse'
              examples:
                ListConfigurationRevisions200Example:
                  summary: Default ListConfigurationRevisions 200 response
                  x-microcks-default: true
                  value:
                    NextToken: example-value
                    Revisions: example-value
        '480':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                ListConfigurationRevisions480Example:
                  summary: Default ListConfigurationRevisions 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: UnauthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedException'
              examples:
                ListConfigurationRevisions481Example:
                  summary: Default ListConfigurationRevisions 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                ListConfigurationRevisions482Example:
                  summary: Default ListConfigurationRevisions 482 response
                  x-microcks-default: true
                  value: {}
        '483':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
              examples:
                ListConfigurationRevisions483Example:
                  summary: Default ListConfigurationRevisions 483 response
                  x-microcks-default: true
                  value: {}
        '484':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                ListConfigurationRevisions484Example:
                  summary: Default ListConfigurationRevisions 484 response
                  x-microcks-default: true
                  value: {}
        '485':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                ListConfigurationRevisions485Example:
                  summary: Default ListConfigurationRevisions 485 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: arn
        in: path
        required: true
        description: "\n            <p>The Amazon Resource Name (ARN) that uniquely identifies an MSK configuration and all of its revisions.</p>"
        schema:
          type: string
      - name: maxResults
        in: query
        required: false
        description: "\n            <p>The maximum number of results to return in the response. If there are more results, the response includes a NextToken parameter.</p>"
        schema:
          type: integer
          minimum: 1
          maximum: 100
      - name: nextToken
        in: query
        required: false
        description: "\n            <p>The paginated results marker. When the result of the operation is truncated, the call returns NextToken in the response. \n            To get the next batch, provide this token in your next request.</p>"
        schema:
          type: string
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      summary: Amazon MSK List Configuration Revisions
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Configurations
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    ConfigurationRevision:
      type: object
      required:
      - Revision
      - CreationTime
      properties:
        CreationTime:
          allOf:
          - $ref: '#/components/schemas/__timestampIso8601'
          - xml:
              name: creationTime
            description: "\n            <p>The time when the configuration revision was created.</p>"
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: "\n            <p>The description of the configuration revision.</p>"
        Revision:
          allOf:
          - $ref: '#/components/schemas/__long'
          - xml:
              name: revision
            description: "\n            <p>The revision number.</p>"
      description: "\n            <p>Describes a configuration revision.</p>"
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    ListConfigurationRevisionsResponse:
      type: object
      properties:
        NextToken:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: nextToken
            description: "\n            <p>Paginated results marker.</p>"
        Revisions:
          allOf:
          - $ref: '#/components/schemas/__listOfConfigurationRevision'
          - xml:
              name: revisions
            description: "\n            <p>List of ConfigurationRevision objects.</p>"
    CreateConfigurationResponse:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: "\n            <p>The Amazon Resource Name (ARN) of the configuration.</p>"
        CreationTime:
          allOf:
          - $ref: '#/components/schemas/__timestampIso8601'
          - xml:
              name: creationTime
            description: "\n            <p>The time when the configuration was created.</p>"
        LatestRevision:
          allOf:
          - $ref: '#/components/schemas/ConfigurationRevision'
          - xml:
              name: latestRevision
            description: "\n            <p>Latest revision of the configuration.</p>"
        Name:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: name
            description: "\n            <p>The name of the configuration.</p>"
        State:
          allOf:
          - $ref: '#/components/schemas/ConfigurationState'
          - xml:
              name: state
            description: "\n            <p>The state of the configuration. The possible states are ACTIVE, DELETING, and DELETE_FAILED. </p>"
    __listOfConfigurationRevision:
      type: array
      items:
        $ref: '#/components/schemas/ConfigurationRevision'
    __long:
      type: integer
    UpdateConfigurationResponse:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: "\n            <p>The Amazon Resource Name (ARN) of the configuration.</p>"
        LatestRevision:
          allOf:
          - $ref: '#/components/schemas/ConfigurationRevision'
          - xml:
              name: latestRevision
            description: "\n            <p>Latest revision of the configuration.</p>"
    DeleteConfigurationResponse:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: "\n            <p>The Amazon Resource Name (ARN) that uniquely identifies an MSK configuration.</p>"
        State:
          allOf:
          - $ref: '#/components/schemas/ConfigurationState'
          - xml:
              name: state
            description: "\n            <p>The state of the configuration. The possible states are ACTIVE, DELETING, and DELETE_FAILED. </p>"
    DescribeConfigurationResponse:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: "\n            <p>The Amazon Resource Name (ARN) of the configuration.</p>"
        CreationTime:
          allOf:
          - $ref: '#/components/schemas/__timestampIso8601'
          - xml:
              name: creationTime
            description: "\n            <p>The time when the configuration was created.</p>"
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: "\n            <p>The description of the configuration.</p>"
        KafkaVersions:
          allOf:
          - $ref: '#/components/schemas/__listOf__string'
          - xml:
              name: kafkaVersions
            description: "\n            <p>The versions of Apache Kafka with which you can use this MSK configuration.</p>"
        LatestRevision:
          allOf:
          - $ref: '#/components/schemas/ConfigurationRevision'
          - xml:
              name: latestRevision
            description: "\n            <p>Latest revision of the configuration.</p>"
        Name:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: name
            description: "\n            <p>The name of the configuration.</p>"
        State:
          allOf:
          - $ref: '#/components/schemas/ConfigurationState'
          - xml:
              name: state
            description: "\n            <p>The state of the configuration. The possible states are ACTIVE, DELETING, and DELETE_FAILED. </p>"
    ConfigurationState:
      type: string
      enum:
      - ACTIVE
      - DELETING
      - DELETE_FAILED
      description: "\n            <p>The state of a configuration.</p>"
    InternalServerErrorException: {}
    ListConfigurationsResponse:
      type: object
      properties:
        Configurations:
          allOf:
          - $ref: '#/components/schemas/__listOfConfiguration'
          - xml:
              name: configurations
            description: "\n            <p>An array of MSK configurations.</p>"
        NextToken:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: nextToken
            description: "\n            <p>The paginated results marker. When the result of a ListConfigurations operation is truncated, the call returns NextToken in the response. \n               To get another batch of configurations, provide this token in your next request.</p>"
    __listOfConfiguration:
      type: array
      items:
        $ref: '#/components/schemas/Configuration'
    __blob:
      type: string
    ConflictException: {}
    ForbiddenException: {}
    BadRequestException: {}
    UnauthorizedException: {}
    __timestampIso8601:
      type: string
      format: date-time
    DescribeConfigurationRevisionResponse:
      type: object
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: "\n            <p>The Amazon Resource Name (ARN) of the configuration.</p>"
        CreationTime:
          allOf:
          - $ref: '#/components/schemas/__timestampIso8601'
          - xml:
              name: creationTime
            description: "\n            <p>The time when the configuration was created.</p>"
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: "\n            <p>The description of the configuration.</p>"
        Revision:
          allOf:
          - $ref: '#/components/schemas/__long'
          - xml:
              name: revision
            description: "\n            <p>The revision number.</p>"
        ServerProperties:
          allOf:
          - $ref: '#/components/schemas/__blob'
          - xml:
              name: serverProperties
            description: "\n            <p>Contents of the <filename>server.properties</filename> file. When using the API, you must ensure that the contents of the file are base64 encoded. \n               When using the AWS Management Console, the SDK, or the AWS CLI, the contents of <filename>server.properties</filename> can be in plaintext.</p>"
    NotFoundException: {}
    Configuration:
      type: object
      required:
      - Description
      - LatestRevision
      - CreationTime
      - KafkaVersions
      - Arn
      - Name
      - State
      properties:
        Arn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: arn
            description: "\n            <p>The Amazon Resource Name (ARN) of the configuration.</p>"
        CreationTime:
          allOf:
          - $ref: '#/components/schemas/__timestampIso8601'
          - xml:
              name: creationTime
            description: "\n            <p>The time when the configuration was created.</p>"
        Description:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: description
            description: "\n            <p>The description of the configuration.</p>"
        KafkaVersions:
          allOf:
          - $ref: '#/components/schemas/__listOf__string'
          - xml:
              name: kafkaVersions
            description: "\n            <p>An array of the versions of Apache Kafka with which you can use this MSK configuration. You can use this configuration for an MSK cluster only if the Apache Kafka version specified for the cluster appears in this array.</p>"
        LatestRevision:
          allOf:
          - $ref: '#/components/schemas/ConfigurationRevision'
          - xml:
              name: latestRevision
            description: "\n            <p>Latest revision of the configuration.</p>"
        Name:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: name
            description: "\n            <p>The name of the configuration.</p>"
        State:
          allOf:
          - $ref: '#/components/schemas/ConfigurationState'
          - xml:
              name: state
            description: "\n            <p>The state of the configuration. The possible states are ACTIVE, DELETING, and DELETE_FAILED. </p>"
      description: "\n            <p>Represents an MSK Configuration.</p>"
    ServiceUnavailableException: {}
    TooManyRequestsException: {}
    __string:
      type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/kafka/
x-hasEquivalentPaths: true
